Testes de Usuario e validação de CPF e Email duplicados
arthurpbelato/TratoFeito pull request #30
Opened 2021-05-06 18:51 UTC by arthurpbelato

2021-05-06 19:42 UTC, flaviolehmann requested changes

2021-05-06 19:42 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/builder/UsuarioBuilder.java
> +import com.colatina.turmaformacao.tratofeito.service.repositorio.UsuarioRepositorio;
`import com.colatina.turmaformacao.tratofeito.service.repositorio.UsuarioRepositorio;`

import não utilizado.

2021-05-06 19:42 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/UsuarioRecursoIT.java
> +                .delete(URL + "/" + usuario.getId().toString())
- não seria melhor importar o delete 'staticamente' como foi feito nos outros?
- Esse `.toString()` é necessário? O casting já não é feito automaticamente?

2021-05-06 19:42 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/UsuarioRecursoIT.java
> +        usuarioRepositorio.deleteAll();
limpar a customização dentro do @BeforeEach

2021-05-06 19:42 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/UsuarioRecursoIT.java
> +        Usuario usuario = usuarioBuilder.construir();
variável `Usuario usuario` não utilizada, pode chamar somente o método `usuarioBuilder.construir();` sem tratar o retorno.

2021-05-06 19:42 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/UsuarioRecursoIT.java
> +                .andExpect(status().isOk());
adicionar também um `.andExpect` verificando o tamanho da lista

2021-05-06 19:42 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/UsuarioRecursoIT.java
> +        usuario.setNome("Atualizado");
utilizar o customizar conforme foi feito no método `salvarEmailDuplicado`.

2021-05-06 19:42 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/UsuarioRecursoIT.java
> +        }).construirEntidade();
chaves são desnecessárias quando a lambda function possui somente uma linha

2021-05-06 20:35 UTC, arthurpbelato commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/builder/UsuarioBuilder.java
> +import com.colatina.turmaformacao.tratofeito.service.repositorio.UsuarioRepositorio;
feito

2021-05-06 20:37 UTC, arthurpbelato commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/UsuarioRecursoIT.java
> +                .delete(URL + "/" + usuario.getId().toString())
feito

2021-05-06 20:37 UTC, arthurpbelato commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/UsuarioRecursoIT.java
> +        Usuario usuario = usuarioBuilder.construir();
feito

2021-05-06 20:39 UTC, arthurpbelato commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/UsuarioRecursoIT.java
> +        }).construirEntidade();
feito

2021-05-06 20:43 UTC, arthurpbelato commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/UsuarioRecursoIT.java
> +                .andExpect(status().isOk());
feito

2021-05-06 20:51 UTC, arthurpbelato commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/UsuarioRecursoIT.java
> +        usuario.setNome("Atualizado");
feito

2021-05-06 21:20 UTC, arthurpbelato commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/UsuarioRecursoIT.java
> +        usuario.setNome("Atualizado");
o método construir entidade, que seria o método a ser utilizado para recuperar o objeto em memória, não permite customização. Chrysthian permitiu a permanência da linha 75

2021-05-07 00:00 UTC, flaviolehmann approved these changes

2021-05-07 00:01 UTC, merged