Nicholas branch testes
arthurpbelato/TratoFeito pull request #33
Opened 2021-05-07 18:11 UTC by nyckols

![image](https://user-images.githubusercontent.com/69114476/117491254-55fabf80-af46-11eb-88f5-02b01d5ef63c.png)
![image](https://user-images.githubusercontent.com/69114476/117491357-79be0580-af46-11eb-874e-2866baab82ed.png)

2021-05-07 22:55 UTC, flaviolehmann requested changes

2021-05-07 22:55 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/ItemRecursoIT.java
> +    private int itemRepositorioCount;
Exite algum motivo específico pra ter mantido essa variável no tipo `int` ?
Se não, trocar para `Long`, assim evita o casting na linha 54.

2021-05-07 22:55 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/ItemRecursoIT.java
> +                .content(TestUtil.convertObjectToJsonBytes(itemMapper.toDto(entidade))))
método GET não deveria conter corpo. O Id de entidade não seria o suficiente para testar esse método?

2021-05-07 22:55 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/ItemRecursoIT.java
> +        entidade.setCategoria(categoriaRepositorio.findById(2L).orElse(null));
Os métodos de testes devem ser mantidos o mais puro possível. Jogue toda essa lógica para dentro do builder, essa é a função dele. É tranquilo criar um método `criarItemComImagem` ou algo assim dentro do builder e chamar ele.

2021-05-07 23:23 UTC, nyckols commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/ItemRecursoIT.java
> +                .content(TestUtil.convertObjectToJsonBytes(itemMapper.toDto(entidade))))
OK

2021-05-07 23:27 UTC, nyckols commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/ItemRecursoIT.java
> +    private int itemRepositorioCount;
Existe um motivo específico pra ser mantido. Eu utilizo a variável itemRepositorioCount como parâmetro em hasSize() na linha 72.

2021-05-07 23:37 UTC, nyckols commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/ItemRecursoIT.java
> +        entidade.setCategoria(categoriaRepositorio.findById(2L).orElse(null));
OK

2021-05-08 00:21 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/ItemRecursoIT.java
> +    private int itemRepositorioCount;
blz. Já que removeu a injeção de `categoriaRepositorio`, remova também o import dela.

2021-05-08 14:41 UTC, nyckols commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/ItemRecursoIT.java
> +    private int itemRepositorioCount;
OK

2021-05-08 20:50 UTC, merged