Testes Baiscos Oferta
arthurpbelato/TratoFeito pull request #35
Opened 2021-05-10 02:23 UTC by Aleahpar

2021-05-10 12:26 UTC, flaviolehmann requested changes

2021-05-10 12:26 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/builder/ItemBuilder.java
> +import com.colatina.turmaformacao.tratofeito.service.dominio.enums.SituacaoEnum;
Import não utilizado

2021-05-10 12:26 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/builder/OfertaBuilder.java
> +    }
método muito grande, crie outros métodos privados menores para funções como criar e customizar usuário alvo, item alvo...

2021-05-10 12:26 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/OfertaRecursoIT.java
> +//    }
Remover código comentado

2021-05-10 12:26 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/OfertaRecursoIT.java
> +        oferta.setItem(item);
Como geralmente toda oferta tem 1 item, talvez seja melhor adicionar esse item por padrão no construirEntidade em OfertaBuilder, assim ajudaria os próximos testes e removeria 2 linhas de código desse teste

2021-05-10 12:26 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/OfertaRecursoIT.java
> +        getMockMvc().perform(get( "/api/ofertas" + "/" + oferta.getId().toString())
esse .toString() é necessário?

2021-05-10 12:26 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/OfertaRecursoIT.java
> +        getMockMvc().perform(get("/api/ofertas")
Criar uma constante na classe (algo como `API_URL`) para armazenar a string "/api/ofertas" que é usada repetidamente na classe

2021-05-10 12:26 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/recurso/OfertaRecursoIT.java
> +                + oferta.getId().toString())
esse `.toString()` é necessário?

2021-05-10 12:26 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/builder/OfertaBuilder.java
> +        usuarioBuilder.removerCustomizacao();
o `.removerCustomizacao();` só é necessário caso seja chamado o método `.customizar()`

2021-05-10 12:26 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/builder/OfertaBuilder.java
> +    private ItemServico itemServico;
Verifique se todas as injeções são necessárias. Aparentemente `ItemServico` e `ItemMapper` não estão sendo usados.

2021-05-10 12:26 UTC, flaviolehmann commented on service/pom.xml
> -			</exclusions>
por que foi necessário remover essa exclusion?

2021-05-13 17:21 UTC, Aleahpar commented
![cleaninstall](https://user-images.githubusercontent.com/58275904/118161837-6e5f5400-b3f6-11eb-8bdd-b1d600c8dab0.png)
![intellij](https://user-images.githubusercontent.com/58275904/118161842-70291780-b3f6-11eb-8d29-05dc3784ca5f.png)

2021-05-17 11:48 UTC, flaviolehmann commented on service/src/main/java/com/colatina/turmaformacao/tratofeito/service/servico/OfertaServico.java
> +import com.colatina.turmaformacao.tratofeito.service.dominio.Situacao;
`import com.colatina.turmaformacao.tratofeito.service.dominio.Situacao;`

parece não estar sendo utilizado

2021-05-17 11:48 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/builder/OfertaBuilder.java
> +        return item;
retorne diretamente itemBuilder.persistir(item); :
`return itemBuilder.persistir(item);`

2021-05-17 11:48 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/builder/OfertaBuilder.java
> +        return usuario;
mesma coisa do comment acima

2021-05-17 11:48 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/builder/OfertaBuilder.java
> +        return item;
mesma coisa do comment acima

2021-05-17 11:48 UTC, flaviolehmann commented on service/src/test/java/com/colatina/turmaformacao/tratofeito/service/builder/OfertaBuilder.java
> +//        return ofertaRepositorio.saveAndFlush(entidade);
bloco de código comentado. remover.

2021-05-17 17:34 UTC, Aleahpar commented on service/src/main/java/com/colatina/turmaformacao/tratofeito/service/servico/OfertaServico.java
> +import com.colatina.turmaformacao.tratofeito.service.dominio.Situacao;
estou usando na linha 94 pra setar a situacao
oferta.setSituacao(new Situacao(2L));

2021-05-17 21:24 UTC, merged